stages:
  - test

rust-latest:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose --no-default-features # no_std
    - cargo test --verbose --no-default-features --features rand,serde # no_std
    - cargo test --verbose --all-features

rust-beta:
  stage: test
  image: rustdocker/rust:beta
  script:
    - cargo test --verbose --no-default-features # no_std
    - cargo test --verbose --no-default-features --features rand,serde # no_std
    - cargo test --verbose --all-features

rust-nightly:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo test --verbose --no-default-features # no_std
    - cargo test --verbose --no-default-features --features rand,serde # no_std
    - cargo test --verbose --all-features
  allow_failure: true
